spring.application.name=diet_mgmt
spring.datasource.url=jdbc:mysql://localhost:3306/dietdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
